### ISSUE TITLE
Add 2023-05-24 DataCite presentation 

### ISSUE THREAD

**Issue by pdurbin** [hermes-hmc/project#16]
It would be nice to update https://project.software-metadata.pub/presentations.html with the recently DataCite presentation.

The HERMES talk starts here: https://youtu.be/LaUdaQ-lI1E?t=2991

I don't know if it makes sense to link specifically to the demo, but it's here: https://youtu.be/LaUdaQ-lI1E?t=4008 (I really appreciated the demo!) ❤️ 

As I'm sure you folks know, the slides are here: https://doi.org/10.5281/zenodo.7963967

**Comment by poikilotherm** [comment]
@pdurbin it should have been online before you opened the issue? (I added it myself earlier today)

**Comment by pdurbin** [comment]
Whoops! Sorry, I expected the list to be reverse chronological (newest on top)! Closing! Sorry for the noise!

**Comment by poikilotherm** [comment]
Thanks for the suggestion to reverse the order. Good idea - that list grew quite a bit over the last two years.
